name: QC Pipeline

on:
  push:
    branches:
      - main

jobs:
  qc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js (Optional, only if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the version you require
          cache: 'npm' # Only include this line if you need to cache node_modules

      - name: Install dependencies (Optional, only if needed)
        if: steps.set-up-node.outputs.cache-hit != 'true'
        run: npm install
        
      - name: HTML Validation
        run: npx vnu-jar --verbose posts/*.html index.html
        continue-on-error: true

      - name: CSS Linting
        run: npx stylelint '**/*.css'
        continue-on-error: true

      - name: Broken Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: '.'
        continue-on-error: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Deploy the root directory
          #cname: yourdomain.com

