name: QC Pipeline

on:
  push:
    branches:
      - main

jobs:
  qc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Create package.json
        run: |
          echo '{"dependencies": {}}' > package.json

      - name: Install dependencies
        run: npm install vnu-jar stylelint
        
      - name: HTML Validation
        run: npx vnu-jar --verbose posts/*.html index.html
        continue-on-error: true

      - name: CSS Linting
        run: npx stylelint '**/*.css'
        continue-on-error: true

      - name: Broken Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: '.'
        continue-on-error: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ 
